### ISSUE TITLE
Endpoints not registered using --qi-url

### ISSUE THREAD

**Issue by piccinnigius** [aldebaran/robot-jumpstarter#2]
I've made a python service that got registered correctly when running on pepper (Working from qicli, ch, etc) but when i try to execute it from my computer (Ubuntu) it's endpoints doesn't point to my ip but only to 127.0.0.1 and i cant work with it from the robot

any suggestion?
thanks in advance

**Comment by EmileKroeger** [comment]
Hmm, doesn't ring a bell, *normally* that should work, which version of the NAOqi (for Pepper and for the Python SDK) ? Maybe your computer has a firewall that's blocking some ports ?

**Comment by piccinnigius** [comment]
naoqi is 2.5, on windows the same script works good. i think that's some issue with Ubuntu 18.10. i've tried to stop all firewalls but nothing change
